### ISSUE TITLE
package aml.ontology; class Ontology

### ISSUE THREAD

**Issue by OumaimaUnige** [AgreementMakerLight/AML-Compound#1]
Hi,
I would to thank you first for your work and for making your code open. I have an issue with Class Ontology:

I want to use your code to try another way of alignment.So i have 2 main questions:
1. for(OWLAnnotation annotation : c.getAnnotations(o)) 
Set<OWLClassExpression> equivClasses = c.getEquivalentClasses(o);
c.getDisjointClasses(o); ...
The error is that the gets methods are not defined in the OWLCLass.
Can you please help me on this. 

2. What is the startegy behind the BK ontology? because, The AML mucher offer a BK alignmnet and the AML compond align 3 ontologies, can you please explain the difference ? Thank you very much

**Comment by OumaimaUnige** [comment]
I resolved the first question :D  OWL API 4 does not offer these methods. 
Can you please explain the secend question .

**Comment by AgreementMakerLight** [comment]
Hi.

First of all, please note that GitHub's issue reporting functionality is intended for reporting issues with the code/material published in GitHub, such as code bugs. It is not a forum for asking questions to the authors of said code/material.
Issues are public, as is all content in GitHub, and by reporting an issue, you may lead other potential users to feel discouraged about using the code/material in question, under the assumption that, because it has open issues, it is not stable. 
In the future, if you need feedback or explanations from the authors, please track down their emails and email them directly, as that is the correct and polite thing to do.

Regarding your first question, as you found out, AML is still using OWL API 3, and there are several differences between it and OWL API 4. Thus, if you want to use the latter, you will have to make adjustments to the code.

Regarding your second question:
- A BK ontology is an ontology used as a mediator for matching two ontologies. For instance, given ontologies X and Y that I want to match, and an ontology BK, I'll try to find matches between BK and X and between BK and Y, and from those, infer matches between X and Y, under the logic that (BKi <=> Xj) & (BKi <=> Yk)  => (Xj <=> Yk).
- In compound matching, we're trying to capture compound mappings between three ontologies. Given three ontologies X, Y, and Z, we want mappings of the form (Xi + Yj <=> Zk). This is not a common ontology matching scenario, but it is relevant for some particular applications.

As I said above, if you need further feedback on AgreementMakerLight, please contact us directly through email.

Daniel Faria
